[tox]
requires = tox>=4.22
envlist = py{310,311,312,313,314},pypy{310,311},codestyle,lint,typecheck

[testenv]
commands = pytest {posargs}
dependency_groups = test

[testenv:codestyle]
basepython = python3.10
commands =
    ruff format --check {posargs:.}
dependency_groups = lint

[testenv:lint]
basepython = python3.10
commands = ruff check {posargs:.}
dependency_groups = lint

[testenv:typecheck]
basepython = python3.10
commands = mypy --show-error-codes scripts tldextract tests
dependency_groups = typecheck
